using FMODUtilityPackage.Core;

namespace FMODUtilityPackage.Enums
{
	// ReSharper disable InconsistentNaming
	/// <summary>
	/// All FMOD events, these are automatically generated by the <see cref="AudioManager"/>
	/// </summary>
	public enum AudioEventType // Automatically generated from FMOD events, do not edit! (Open the AudioManager inspector or use the "FMOD/Import Events" menu to regenerate)
	{
		/// <FMODEventPath>
		/// event:/TestEvent
		/// </FMODEventPath>
		TestEvent,

		/// <FMODEventPath>
		/// event:/Music/Main Menu
		/// </FMODEventPath>
		Music_Main_Menu,

		/// <FMODEventPath>
		/// event:/Music/Gameplay
		/// </FMODEventPath>
		Music_Gameplay,

		/// <FMODEventPath>
		/// event:/Sound Effects/Animals/Rooster
		/// </FMODEventPath>
		Sound_Effects_Animals_Rooster,

		/// <FMODEventPath>
		/// event:/Sound Effects/Animals/Cow
		/// </FMODEventPath>
		Sound_Effects_Animals_Cow,

		/// <FMODEventPath>
		/// event:/Sound Effects/NPCs/Cheer
		/// </FMODEventPath>
		Sound_Effects_NPCs_Cheer,

		/// <FMODEventPath>
		/// event:/Sound Effects/Animals/Pig
		/// </FMODEventPath>
		Sound_Effects_Animals_Pig,

		/// <FMODEventPath>
		/// event:/Sound Effects/Time/TimeSlowdown
		/// </FMODEventPath>
		Sound_Effects_Time_TimeSlowdown,

		/// <FMODEventPath>
		/// event:/Sound Effects/Animals/Dog
		/// </FMODEventPath>
		Sound_Effects_Animals_Dog,

		/// <FMODEventPath>
		/// event:/Sound Effects/NPCs/Talksound
		/// </FMODEventPath>
		Sound_Effects_NPCs_Talksound,

		/// <FMODEventPath>
		/// event:/Sound Effects/Player/ReverseTime
		/// </FMODEventPath>
		Sound_Effects_Player_ReverseTime,

		/// <FMODEventPath>
		/// event:/Sound Effects/UI/Click
		/// </FMODEventPath>
		Sound_Effects_UI_Click,

		/// <FMODEventPath>
		/// event:/Sound Effects/NPCs/npcDeath
		/// </FMODEventPath>
		Sound_Effects_NPCs_npcDeath,

		/// <FMODEventPath>
		/// event:/Sound Effects/Player/Death_GameOver
		/// </FMODEventPath>
		Sound_Effects_Player_Death_GameOver,

		/// <FMODEventPath>
		/// event:/Sound Effects/Player/Footsteps
		/// </FMODEventPath>
		Sound_Effects_Player_Footsteps,

		/// <FMODEventPath>
		/// event:/Sound Effects/Player/ChangeDirection
		/// </FMODEventPath>
		Sound_Effects_Player_ChangeDirection,

		/// <FMODEventPath>
		/// event:/Sound Effects/NPCs/npcFootstep
		/// </FMODEventPath>
		Sound_Effects_NPCs_npcFootstep,

		/// <FMODEventPath>
		/// event:/Sound Effects/NPCs/npcAlertBeep
		/// </FMODEventPath>
		Sound_Effects_NPCs_npcAlertBeep,

		/// <FMODEventPath>
		/// event:/Sound Effects/Animals/DragonRoar
		/// </FMODEventPath>
		Sound_Effects_Animals_DragonRoar,

		/// <FMODEventPath>
		/// event:/Sound Effects/Animals/DragonWing
		/// </FMODEventPath>
		Sound_Effects_Animals_DragonWing,

		/// <FMODEventPath>
		/// event:/Sound Effects/NPCs/horseFootstep
		/// </FMODEventPath>
		Sound_Effects_NPCs_horseFootstep,

		/// <FMODEventPath>
		/// event:/Sound Effects/NPCs/dragonFire
		/// </FMODEventPath>
		Sound_Effects_NPCs_dragonFire,

		/// <FMODEventPath>
		/// event:/Sound Effects/Time/clockTick
		/// </FMODEventPath>
		Sound_Effects_Time_clockTick,

		/// <FMODEventPath>
		/// event:/Sound Effects/NPCs/donkeyCart
		/// </FMODEventPath>
		Sound_Effects_NPCs_donkeyCart,

		/// <FMODEventPath>
		/// event:/Sound Effects/NPCs/windMill
		/// </FMODEventPath>
		Sound_Effects_NPCs_windMill,
	}
}