using FMODUtilityPackage.Core;

namespace FMODUtilityPackage.Enums
{
	// ReSharper disable InconsistentNaming
	/// <summary>
	/// All FMOD events, these are automatically generated by the <see cref="AudioManager"/>
	/// </summary>
	public enum AudioEventType // Automatically generated from FMOD events, do not edit! (Open the AudioManager inspector or use the "FMOD/Import Events" menu to regenerate)
	{
		/// <FMODEventPath>
		/// event:/TestEvent
		/// </FMODEventPath>
		TestEvent,

		/// <FMODEventPath>
		/// event:/Music/Main Menu
		/// </FMODEventPath>
		Music_Main_Menu,

		/// <FMODEventPath>
		/// event:/Music/Gameplay
		/// </FMODEventPath>
		Music_Gameplay,

		/// <FMODEventPath>
		/// event:/Sound Effects/Animals/Rooster
		/// </FMODEventPath>
		Sound_Effects_Animals_Rooster,

		/// <FMODEventPath>
		/// event:/Sound Effects/Footsteps
		/// </FMODEventPath>
		Sound_Effects_Footsteps,

		/// <FMODEventPath>
		/// event:/Sound Effects/Animals/Cow
		/// </FMODEventPath>
		Sound_Effects_Animals_Cow,

		/// <FMODEventPath>
		/// event:/Sound Effects/NPCs/Cheer
		/// </FMODEventPath>
		Sound_Effects_NPCs_Cheer,

		/// <FMODEventPath>
		/// event:/Sound Effects/Animals/Pig
		/// </FMODEventPath>
		Sound_Effects_Animals_Pig,

		/// <FMODEventPath>
		/// event:/Sound Effects/Time/TimeSlowdown
		/// </FMODEventPath>
		Sound_Effects_Time_TimeSlowdown,

		/// <FMODEventPath>
		/// event:/Sound Effects/Animals/Dog
		/// </FMODEventPath>
		Sound_Effects_Animals_Dog,

		/// <FMODEventPath>
		/// event:/Sound Effects/NPCs/Talksound
		/// </FMODEventPath>
		Sound_Effects_NPCs_Talksound,
	}
}